### PR TITLE
move fields to required arguments

### PR DESCRIPTION
**Pull request by Kosmas**

### CODE REVIEW

**Comment by falzm** [comment]
Hi, can you elaborate on the reason that motivates this change? The documentation is accurate, `api_endpoint` and `sos_endpoint` are optional attributes as they have working default values:

```hcl
# cat packer.pkr.hcl
variable "api_key" { default = "" }
variable "api_secret" { default = "" }
variable "zone" { default = "ch-dk-2" }

source "file" "test" {
  source = "test.qcow2_"
  target = "test.qcow2"
}

build {
  sources = ["source.file.test"]

  post-processor "exoscale-import" {
    api_key = var.api_key
    api_secret = var.api_secret
    image_bucket = "eat-templates"
    template_zone = var.zone
    template_name = "packer-post-processor-exoscale-import"
    template_username = "ubuntu"
  }
}
```

```console
$ packer build packer.pkr.hcl
file: output will be in this color.

==> file: Copying test.qcow2_ to test.qcow2
==> file: Copied 197120 bytes
==> file: Running post-processor:  (type exoscale-import)
==> file (exoscale-import): Uploading template image
test.qcow2 192.50 KiB / 192.50 KiB [==============================================] 100.00% 1s
==> file (exoscale-import): Registering Compute instance template
Build 'file' finished.

==> Builds finished. The artifacts of successful builds are:
--> file: packer-post-processor-exoscale-import @ ch-dk-2 (df8d0297-7ea1-4d9c-8fac-cbd14e5d78b2)
```

**Comment by Kosmas** [comment]
Hi @falzm ,

The original one was about the template description (https://github.com/hashicorp/packer/blob/6d1a1461435512160f56d858c3d4cecc5ae2aaf5/post-processor/exoscale-import/post-processor.go#L88) that is required in packer but not in your documentation.
While trying other fields it worked with adding the two additonal ones api and sos endpoints. Now that I have it working, I will try again without these two but the the template_description in there. 

So perhaps, I close this one and reopen the original one (https://github.com/exoscale/packer-post-processor-exoscale-import/pull/5)

Update. Just tried by removing these two fields from the packer.json and it does not work for me.

**Comment by Kosmas** [comment]
Without api and sos endpoints:

`==> qemu: Running post-processor: exoscale-import
    qemu (exoscale-import): Uploading template image
vault.qcow2 5.00 MiB / 526.81 MiB [=>--------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.95% 01m43s
vault.qcow2 5.00 MiB / 526.81 MiB [=>------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.95% 1s
2020/08/07 16:26:57 [INFO] (telemetry) ending exoscale-import
2020/08/07 16:26:57 Deleting original artifact for build 'qemu'

* Post-processor failed: unable to upload image: NoSuchKey: The specified key does not exist
        status code: 404, request id: 5249cc87-4e7c-4064-b775-ed0f3348c474, host id: 5249cc87-4e7c-4064-b775-ed0f3348c474
Build 'qemu' errored: 1 error(s) occurred:
2020/08/07 16:26:57 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:

2020/08/07 16:26:57 machine readable: qemu,error []string{"1 error(s) occurred:\n\n* Post-processor failed: unable to upload image: NoSuchKey: The specified key does not exist\n\tstatus code: 404, request id: 5249cc87-4e7c-4064-b775-ed0f3348c474, host id: 5249cc87-4e7c-4064-b775-ed0f3348c474"}

* Post-processor failed: unable to upload image: NoSuchKey: The specified key does not exist
        status code: 404, request id: 5249cc87-4e7c-4064-b775-ed0f3348c474, host id: 5249cc87-4e7c-4064-b775-ed0f3348c474
==> Builds finished but no artifacts were created.
2020/08/07 16:26:57 [INFO] (telemetry) Finalizing.
* Post-processor failed: unable to upload image: NoSuchKey: The specified key does not exist
        status code: 404, request id: 5249cc87-4e7c-4064-b775-ed0f3348c474, host id: 5249cc87-4e7c-4064-b775-ed0f3348c474

==> Some builds didn't complete successfully and had errors:
--> qemu: 1 error(s) occurred:

* Post-processor failed: unable to upload image: NoSuchKey: The specified key does not exist
        status code: 404, request id: 5249cc87-4e7c-4064-b775-ed0f3348c474, host id: 5249cc87-4e7c-4064-b775-ed0f3348c474
`

**Comment by falzm** [comment]
Do you use this external plugin or the post-processor currently integrated in the upstream repository (https://github.com/hashicorp/packer/tree/master/post-processor/exoscale-import)? During the extraction of the integrated post-processor in this dedicated repository we've overhauled the implementation and the new one handles the default attributes value a little more intelligently.

As a result, the issue you're reporting probably relates to the upstream version, as I've demonstrated in my previous comment that this new implementation works as documented – therefore there is no point in modifying the documentation of this project.

However, please note that there is a Pull Request currently open in the upstream Packer repository: https://github.com/hashicorp/packer/pull/9733 We recommend you switching to using this external plugin instead of the built-in one that will be removed in a near future.

**Comment by Kosmas** [comment]
@falzm yes i use the packer one, and it currently only works only if I add the fields that are missing.
I will try to switch to the external plugin.
As you say there is not point in changing the documentation here if it works as it should.
Thought that was an issue here.
Closing the PR here. Sorry :(

**Comment by falzm** [comment]
No worries – this situation is a bit confusing :)

**Pull request closed without merging**
